# Generated by Django 4.1.5 on 2023-02-07 10:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_event_organizer_alter_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventDate',
            field=models.DateField(validators=[events.models.dateValidator]),
        ),
        migrations.AlterField(
            model_name='event',
            name='nbrParticipants',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Number of participants must be a positive')]),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePart', models.DateField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('person', 'event')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='participate',
            field=models.ManyToManyField(related_name='participations', through='events.Participation', to=settings.AUTH_USER_MODEL),
        ),
    ]
